services:
  arb-updater:
    build: .
    container_name: arb-updater
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - arbtool-network

networks:
  arbtool-network:
    external: true
